'use strict'

module.exports = {
  subjectParser: 'angular',
  updateVersion: 'package.json',
  addEntryToChangelog: 'prepend',
  includeCommitWhen: commit => commit.footer['Changelog-Entry'],
  getIncrementLevelFromCommit: commit => commit.footer['Change-Type'],
  changelogFile: 'CHANGELOG.md',
  template: [
    '## v{{version}} - {{date}}',
    '',
    '{{#each commits}}',
    '{{#with footer}}',
    '* {{capitalize Changelog-Entry}}',
    '{{/with}}',
    '{{/each}}',
    ''
  ].join('\n'),
  header:
    '# Change Log\n\nAll notable changes to this project will be documented in this file automatically by Versionist. DO NOT EDIT THIS FILE MANUALLY!\nThis project adheres to [Semantic Versioning](http://semver.org/).\n\n'
}
